project/models.py
from project import db 

class Strain(db.Model):

	__tablename__ = "strains"

	id = db.Column(db.Integer, primary_key = True)
	name = db.Column(db.Text)
	image = db.Column(db.Text)
	strain_type = db.Column(db.Text)
	medicinal_traits = db.Column(db.Text)
	description = db.Column(db.Text)
	inflammation = db.Column(db.Boolean)
	headache = db.Column(db.Boolean)
	spasm = db.Column(db.Boolean)
	appetite = db.Column(db.Boolean)
	anxiety = db.Column(db.Boolean)
	depression = db.Column(db.Boolean)
	insomnia = db.Column(db.Boolean)
	pain = db.Column(db.Boolean)

	def __init__(self, name, image, strain_type, medicinal_traits, description, inflammation, headache, spasm, appetite, anxiety, depression, insomnia, pain):
		self.name = name
		self.image = image
		self.strain_type = strain_type
		self.medicinal_traits = medicinal_traits
		self.description = description
		self.inflammation = inflammation
		self.headache = headache
		self.spasm = spasm
		self.appetite = appetite
		self.anxiety = anxiety
		self.depression = depression
		self.insomnia = insomnia
		self.pain = pain

project/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, validators

class  RegisterForm(FlaskForm):
	StringField
	PasswordField
	validators
	pass

app.py
from project import  app












if __name__ == '__main__':
    app.run(debug=True, port=4000)

project/__init__.py
from flask import Flask, redirect
from flask_sqlalchemy import SQLAlchemy
import os

app = Flask(__name__)


if os.environ.get('ENV') == 'production':
    debug = False
    app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get('DATABASE_URL')
else:
    debug = True
    app.config['SQLALCHEMY_DATABASE_URI'] = 'postgres://localhost/deewit'

app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SECRET_KEY'] = "shhhh"
app.config['TEMPLATES_AUTO_RELOAD'] = True

db = SQLAlchemy(app)

from project.strains.views import strains_blueprint


app.register_blueprint(strains_blueprint, url_prefix='/strains')

@app.route('/')
def root():
    return redirect('/strains/home')

project/strains/views.py
from flask import Flask, render_template, request, redirect, url_for, flash, Blueprint, jsonify
from project import db
from scraper import Strain


strains_blueprint = Blueprint(
	'strains',
	__name__,
	template_folder = 'templates')



@strains_blueprint.route('/home', methods=['GET', 'POST'])
def home():
	return render_template('strains/strains.html')


@strains_blueprint.route('/results', methods=['GET', 'POST'])
def results():
	raw = request.args.get('info')
	raw = raw.replace("[", "")
	raw = raw.replace(']', '')
	raw = raw.replace('"', '')
	raw = raw.replace(',', '')
	data = list(raw)
	one = ['f', 't', 't', 't', 't', 't', 't', 't']
	two = ['t', 't', 't', 't', 't', 'f', 't', 't']
	three = ['t', 't', 't', 'f', 't', 't', 't', 't']
	four = ['f', 't', 't', 'f', 't', 'f', 't', 't']
	five = ['t', 't', 't', 'f', 't', 'f', 't', 't']
	six = ['f', 't', 't', 'f', 't', 't', 't', 't']
	seven = ['f', 't', 't', 't', 't', 'f', 't', 't']
	eight = ['t', 't', 't', 't', 't', 't', 't', 't']
	onecount = 0
	twocount = 0
	threecount = 0
	fourcount = 0
	fivecount = 0
	sixcount = 0
	sevencount = 0
	eightcount = 0

	for idx, val in enumerate(data):
		if data[idx] == one[idx]:
			onecount+=1
	for idx, val in enumerate(data):
		if data[idx] == two[idx]:
			twocount+=1
	for idx, val in enumerate(data):
		if data[idx] == three[idx]:
			threecount+=1
	for idx, val in enumerate(data):
		if data[idx] == four[idx]:
			fourcount+=1
	for idx, val in enumerate(data):
		if data[idx] == five[idx]:
			fivecount+=1
	for idx, val in enumerate(data):
		if data[idx] == six[idx]:
			sixcount+=1
	for idx, val in enumerate(data):
		if data[idx] == seven[idx]:
			sevencount+=1
	for idx, val in enumerate(data):
		if data[idx] == eight[idx]:
			eightcount+=1

	
	querytype = max(onecount, twocount, threecount, fourcount, fivecount, sixcount, sevencount, eightcount)

	if onecount == querytype:
		results = Strain.query.filter_by(inflammation=False, headache=True, spasm=True, appetite=True, anxiety=True, depression=True, insomnia=True, pain=True).limit(3).all()
		return render_template('strains/results.html', results=results)

	if twocount == querytype:
		results = Strain.query.filter_by(inflammation=True, headache=True, spasm=True, appetite=True, anxiety=True, depression=False, insomnia=True, pain=True).limit(3).all()
		return render_template('strains/results.html', results=results)

	if threecount == querytype:
		results = Strain.query.filter_by(inflammation=True, headache=True, spasm=True, appetite=False, anxiety=True, depression=True, insomnia=True, pain=True).limit(3).all()
		return render_template('strains/results.html', results=results)

	if fourcount == querytype:
		results = Strain.query.filter_by(inflammation=False, headache=True, spasm=True, appetite=False, anxiety=True, depression=False, insomnia=True, pain=True).limit(3).all()
		return render_template('strains/results.html', results=results)

	if fivecount == querytype:
		results = Strain.query.filter_by(inflammation=True, headache=True, spasm=True, appetite=False, anxiety=True, depression=False, insomnia=True, pain=True).limit(3).all()
		return render_template('strains/results.html', results=results)

	if sixcount == querytype:
		results = Strain.query.filter_by(inflammation=False, headache=True, spasm=True, appetite=False, anxiety=True, depression=True, insomnia=True, pain=True).limit(3).all()
		return render_template('strains/results.html', results=results)

	if sevencount == querytype:
		results = Strain.query.filter_by(inflammation=False, headache=True, spasm=True, appetite=True, anxiety=True, depression=False, insomnia=True, pain=True).limit(3).all()
		return render_template('strains/results.html', results=results)

	if eightcount == querytype:
		results = Strain.query.filter_by(inflammation=True, headache=True, spasm=True, appetite=True, anxiety=True, depression=True, insomnia=True, pain=True).limit(3).all()
		return render_template('strains/results.html', results=results)


	from IPython import embed; embed()
	pass

@strains_blueprint.route('/show')
def show():
	strains = Strain.query.all()
	return render_template('strains/show.html', strains=strains)

@strains_blueprint.route('/about')
def about():
	return render_template('strains/about.html')

@strains_blueprint.route('/contact')
def contact():
	return render_template('strains/contact.html')

project/strains/templates/strains/about.html
<!DOCTYPE html>
<html>

<head>

    <head>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    </head>
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <style>
    @media (max-width: 9999px) {
        html {
            background: url('http://www.timestuff.de/wp-content/uploads/2016/05/0ckPWb2.jpg') no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
            background-size: 100% 100%;
        }
        
        html,
        body {
            margin: 0;
            height: 100%;
            overflow: hidden
        }
        
        .navlogo{
            margin-top: -9px;
            width: 200px;
            height: 60px;
            display: inline-block;
        }

        #logo{
            height: 120%;
            width: 200px;
        }

        .navitems{
            margin-top: .5vh;
        }

        .navstuff{
            text-align: right;
            margin-right: 2.5vw;
            margin-top: 7px;
            width: 50vw;
            display: inline-block;
            float: right;
            color:black;
            font-family: 'Montserrat', sans-serif;
            text-decoration:none;
        }

        li{
            display: inline-block;
            font-size:2rem;
            margin-left: 2vw;
        }

        li:hover {
        }

        a{
            font-size:0.85em;
            color:black;
            text-decoration:none;
        }
        
        
        #nav {
            background-color: rgba(255, 255, 255, .9);
            width: 100vw;
            height: 60px;
            margin-left: -1vw;
            margin-top: -1vw;
            
            position: center;
            
            display: inline-block;
        }
        
        #bgcover {
            background-color: rgba(0, 0, 0, 0.65);
            width: 100vw;
            height: 100vh;
            margin-top: 0px;
            margin-left: 0px;
            margin-right: 0%;
            padding: 1%;
            position: relative;
        }
    
    
    
    
    
    
    
    
    .pitchwrap {
        width: 99%;
        text-align: center;
        margin-top: 15vh;
        color: white;
        font-family: 'Josefin Sans', sans-serif;
    }
    
    #one {
        font-size: 250%;
        font-weight: bold;
    }
    
    #two {
        margin-top: 4%;
        font-weight: ;
        font-size: 225%;
    }
    
    #three {
        margin-top: 4%;
        font-size: 230%;
    }
    
    button {
        margin-top: 4%;
        padding: 1.5% 0% 1% 0%;
        border-style: solid;
        background: grey;
        border-width: 2px;
        border-radius: 55px;
        border-color: white;
        text-align: center;
        width: 40%;
        height: 35%;
        font-size: 375%;
        font-family: 'Josefin Sans', sans-serif;
        color: white;
        box-shadow: inset 0 1px 4px rgba(0, 0, 0, 0.6);
    }
    
    .btn {
        text-align: center;
    }
    
    button:hover {
        background: #696969;
        cursor: pointer;
    }
    
    button:focus {
        outline: 0;
    }
    
    .field {
        text-align: center;
        font-size: 250%;
        font-weight: bold;
        width: 99%;
        margin-top: 16%;
        color: white;
        font-family: 'Josefin Sans', sans-serif;
    }
    
    .yes1,
    .no1,
    .yes2,
    .no2,
    .yes3,
    .no3,
    .yes4,
    .no4,
    .yes5,
    .no5,
    .yes6,
    .no6,
    .yes7,
    .no7,
    .yes8,
    .no8 {
        width: 6%;
        height: 6%;
        margin-right: 4%;
        margin-left: 4%;
    }
    
    .yes,
    .no,
    .sub1,
    .sub2 {
        width: 6%;
        height: 6%;
        margin-right: 4%;
        margin-left: 4%;
    }    }
    </style>
</head>

<body>
    <div id="bgcover">
        <div id="nav">
            <div class="navlogo">
                <a href="{{url_for('strains.home')}}">
                    <img id="logo" src="http://i.imgur.com/HtDLGnG.png" alt="">
                </a>
            </div>
            <div class="navstuff">
                <ul class="navitems">
                    <li><a href="{{url_for('strains.show')}}">Strains</a></li>
                    <li></li>
                    <li><a href="{{url_for('strains.about')}}">About</a></li>
                    <li></li>
                    <li><a href="{{url_for('strains.contact')}}">Contact</a></li>
                </ul>
            </div>
        </div>
        <div class="pitchwrap">
            
            <div class="pitch" id="two">The idea that sparked the creation of Deew It was conceived by Kyle Brancato early 2016. Kyle saw the change happening in the medical marijuana industry, with more and more people getting access to the plant every day. <br> Bills were being passed left and right, things seemed to be going in the right direction, yet the concept of getting a specific diagnosis was almost non existant. Users would have to use trial and error to find out what strains worked best for them.  </div>
            <div class="pitch" id="two">This is where Deew It comes in. Our algorithms are written to find you the best possible match no matter what your symptoms are. Give it a try, you won't be dissapointed.</div>
            <div class="pitch" id="three">-The Deew It Team</div>
        </div>
    </div>
</body>

</html>

project/strains/templates/strains/contact.html
<!DOCTYPE html>
<html>

<head>

    <head>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    </head>
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <style>
    @media (max-width: 9999px) {
        html {
            background: url('https://s-media-cache-ak0.pinimg.com/originals/2b/c9/21/2bc921c906d805413200c1e34f328d24.jpg') no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
            background-size: 100% 100%;
        }
        
        html,
        body {
            margin: 0;
            height: 100%;
            overflow: hidden
        }
        
        .navlogo{
            margin-top: -9px;
            width: 200px;
            height: 60px;
            display: inline-block;
        }

        #logo{
            height: 120%;
            width: 200px;
        }

        .navitems{
            margin-top: .5vh;
        }

        .navstuff{
            text-align: right;
            margin-right: 2.5vw;
            margin-top: 7px;
            width: 50vw;
            display: inline-block;
            float: right;
            color:black;
            font-family: 'Montserrat', sans-serif;
            text-decoration:none;
        }

        li{
            display: inline-block;
            font-size:2rem;
            margin-left: 2vw;
        }

        li:hover {
        }

        a{
            font-size:0.85em;
            color:black;
            text-decoration:none;
        }
        
        
        #nav {
            background-color: rgba(255, 255, 255, .9);
            width: 100vw;
            height: 60px;
            margin-left: -1vw;
            margin-top: -1vw;
            
            position: center;
            
            display: inline-block;
        }
        
        #bgcover {
            background-color: rgba(0, 0, 0, 0.65);
            width: 100vw;
            height: 100vh;
            margin-top: 0px;
            margin-left: 0px;
            margin-right: 0%;
            padding: 1%;
            position: relative;
        }
    
    
    
    
    
    
    
    .pitchwrap {
        width: 99%;
        text-align: center;
        margin-top: 15vh;
        color: white;
        font-family: 'Josefin Sans', sans-serif;
    }
    
    #one {
        font-size: 250%;
        font-weight: bold;
    }
    
    #two {
        margin-top: 4%;
        font-weight: ;
        font-size: 225%;
    }
    
    #three {
        margin-top: 4%;
        font-size: 230%;
    }
    
    button {
        margin-top: 4%;
        padding: 1.5% 0% 1% 0%;
        border-style: solid;
        background: grey;
        border-width: 2px;
        border-radius: 55px;
        border-color: white;
        text-align: center;
        width: 40%;
        height: 35%;
        font-size: 375%;
        font-family: 'Josefin Sans', sans-serif;
        color: white;
        box-shadow: inset 0 1px 4px rgba(0, 0, 0, 0.6);
    }
    
    .btn {
        text-align: center;
    }
    
    button:hover {
        background: #696969;
        cursor: pointer;
    }
    
    button:focus {
        outline: 0;
    }
    
    .field {
        text-align: center;
        font-size: 250%;
        font-weight: bold;
        width: 99%;
        margin-top: 16%;
        color: white;
        font-family: 'Josefin Sans', sans-serif;
    }
    
    .yes1,
    .no1,
    .yes2,
    .no2,
    .yes3,
    .no3,
    .yes4,
    .no4,
    .yes5,
    .no5,
    .yes6,
    .no6,
    .yes7,
    .no7,
    .yes8,
    .no8 {
        width: 6%;
        height: 6%;
        margin-right: 4%;
        margin-left: 4%;
    }
    
    .yes,
    .no,
    .sub1,
    .sub2 {
        width: 6%;
        height: 6%;
        margin-right: 4%;
        margin-left: 4%;
    }
    .wrapper1,
    .wrapper2,
    .wrapper3 {
        margin-top: 2vh;
        font-family: 'Josefin Sans', sans-serif;
        color: white;
        width: 100%;

    }

    h1{
        margin-top: 2%;
        font-size: 250%;
    }

    p{
        font-size: 300%;
        margin-top: -1%;
    }

    .p2h{
        margin-top: -1.5%;
        font-size: 250%;
    }

    .p2{
        font-size: 200%;
        margin-top: -1%;
    }

    </style>
</head>

<body>
<div id="bgcover">
        <div id="nav">
            <div class="navlogo">
                <a href="{{url_for('strains.home')}}">
                    <img id="logo" src="http://i.imgur.com/HtDLGnG.png" alt="">
                </a>
            </div>
            <div class="navstuff">
                <ul class="navitems">
                    <li><a href="{{url_for('strains.show')}}">Strains</a></li>
                    <li></li>
                    <li><a href="{{url_for('strains.about')}}">About</a></li>
                    <li></li>
                    <li><a href="{{url_for('strains.contact')}}">Contact</a></li>
                </ul>
            </div>
        </div>
        <div class="pitchwrap">
            
            <div class="pitch" id="two">Here at <b>Deew It</b>, we aspire to be the best in what we do, but also acknowledge that theres always room for improvement.</div>
            <div class="pitch" id="three">Send any questions, comments, or suggestions our way through either phone or email.</div>
            <h1>PHONE:</h1>
            <p>951.746.8715</p>
            <h1 class="p2h">EMAIL:</h1>
            <p class="p2">brancatokyle@gmail.com</p>
            <p class="p2">aricliesenfelt@gmail.com(developer)</p>
        </div>
        
    </div>
</body>

</html>

project/strains/templates/strains/strains.html
<!DOCTYPE html>
<html>

<head>

    <head>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='strains.js') }}"></script>
    </head>
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='strains.css') }}">

</head>

<body>
    <div id="bgcover">
        <div id="nav">
            <div class="navlogo">
                <a href="{{url_for('strains.home')}}">
                    <img id="logo" src="http://i.imgur.com/HtDLGnG.png" alt="">
                </a>
            </div>
            <div class="navstuff">
                <ul class="navitems">
                    <li><a href="{{url_for('strains.show')}}">Strains</a></li>
                    <li></li>
                    <li><a href="{{url_for('strains.about')}}">About</a></li>
                    <li></li>
                    <li><a href="{{url_for('strains.contact')}}">Contact</a></li>
                </ul>
            </div>
        </div>
        <div class="pitchwrap">
            <div class="pitch" id="one">The medical marijuana industry is letting us down.</div>
            <div class="pitch" id="two">While medical marijuana itself is becoming more and more accessible, specific diagnosis and <br>treatment is almost unheard of.</div>
            <div class="pitch" id="three">Welcome to <b>Deew It</b>, the first cannabis diagnostics tool made for <i>you</i>, the patient.</div>
        </div>
        <div class="btn">
            <button type="submit">Get Diagnosed</button>
        </div>
        <div class="field first">
            <div class="top1">
                <p>Have you been dealing with Inflammation?</p>
            </div>
            <div class="bottom">
                <a href="#" class="yes1">
                    <img src="http://www.packitup.dk/img/checkmark.png" alt="" class="yes1">
                </a>
                <a href="#" class="no1">
                    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/White_X_in_red_background.svg/2000px-White_X_in_red_background.svg.png" alt="" class="no1">
                </a>
            </div>
        </div>
        <div class="field second">
            <div class="top2">
                <p>Have you been coping with migraines/headaches?</p>
            </div>
            <div class="bottom">
                <a href="#" class="yes2">
                    <img src="http://www.packitup.dk/img/checkmark.png" alt="" class="yes2">
                </a>
                <a href="#" class="no2">
                    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/White_X_in_red_background.svg/2000px-White_X_in_red_background.svg.png" alt="" class="no2">
                </a>
            </div>
        </div>
        <div class="field third">
            <div class="top3">
                <p>Are you looking for relief from seizures/spasms?</p>
            </div>
            <div class="bottom">
                <a href="#" class="yes3">
                    <img src="http://www.packitup.dk/img/checkmark.png" alt="" class="yes3">
                </a>
                <a href="#" class="no3">
                    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/White_X_in_red_background.svg/2000px-White_X_in_red_background.svg.png" alt="" class="no3">
                </a>
            </div>
        </div>
        <div class="field fourth">
            <div class="top4">
                <p>Are you experiencing loss of appetite?</p>
            </div>
            <div class="bottom">
                <a href="#" class="yes4">
                    <img src="http://www.packitup.dk/img/checkmark.png" alt="" class="yes4">
                </a>
                <a href="#" class="no4">
                    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/White_X_in_red_background.svg/2000px-White_X_in_red_background.svg.png" alt="" class="no4">
                </a>
            </div>
        </div>
        <div class="field fifth">
            <div class="top5">
                <p>Are you battling anxiety?</p>
            </div>
            <div class="bottom">
                <a href="#" class="yes5">
                    <img src="http://www.packitup.dk/img/checkmark.png" alt="" class="yes5">
                </a>
                <a href="#" class="no5">
                    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/White_X_in_red_background.svg/2000px-White_X_in_red_background.svg.png" alt="" class="no5">
                </a>
            </div>
        </div>
        <div class="field sixth">
            <div class="top6">
                <p>Are you suffering from depression?</p>
            </div>
            <div class="bottom">
                <a href="#" class="yes6">
                    <img src="http://www.packitup.dk/img/checkmark.png" alt="" class="yes6">
                </a>
                <a href="#" class="no6">
                    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/White_X_in_red_background.svg/2000px-White_X_in_red_background.svg.png" alt="" class="no6">
                </a>
            </div>
        </div>
        <div class="field seventh">
            <div class="top7">
                <p>Do you have trouble falling asleep at night?</p>
            </div>
            <div class="bottom">
                <a href="#" class="yes7">
                    <img src="http://www.packitup.dk/img/checkmark.png" alt="" class="yes7">
                </a>
                <a href="#" class="no7">
                    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/White_X_in_red_background.svg/2000px-White_X_in_red_background.svg.png" alt="" class="no7">
                </a>
            </div>
        </div>
        <div class="field eighth">
            <div class="top8">
                <p>Are you experiencing any kind of physical pain/aching?</p>
            </div>
            <div class="bottom">
                <form class="f1" style="margin: 0; padding: 0; display: inline;" action="{{url_for('strains.results')}}">
                    <input class="valyes" style="display: inline;" type="hidden" name="info" value="">
                    <a class="sub1" type="submit" style="display: inline;" href="#" class="yes">
                        <img style="display: inline;" src="http://www.packitup.dk/img/checkmark.png" alt="" class="yes8">
                    </a>
                </form>
                <form class="f2" style="margin: 0; padding: 0; display: inline;" action="{{url_for('strains.results')}}">
                    <input class="valno" style="display: inline;" type="hidden" name="info" value="">
                    <a class="sub2" type="submit" style="display: inline;" href="#" class="no">
                        <img style="display: inline;" src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/White_X_in_red_background.svg/2000px-White_X_in_red_background.svg.png" alt="" class="no8">
                    </a>
                </form>
            </div>
        </div>
    </div>
</body>

</html>